server:
  port: 8080 # 어치피 목으로 실행할 거라 데브랑 겹쳐도 노상관
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
    #   '[hibernate.default_batch_fetch_size]': 100 나중에 사용할 거임
      '[hibernate.format_sql]': true
    show-sql: true
  output: 
    ansi:
      enabled: always
      
logging:
  level:
    '[com.mtcoding.demo]': DEBUG