server:
  port: 8080
  servlet:
    encoding: # json 인코딩 한글
      charset: utf-8
      force: true
  
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL # mysql = mariadb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false # false 로 돼있음
    hibernate:
      ddl-auto: create # 크리에이트 돼 있음
    properties:
    #   '[hibernate.default_batch_fetch_size]': 100 추후 사용
      '[hibernate.format_sql]': true # 쿼리 예쁘게 보기
    show-sql: true # 쿼리 보기
  output: 
    ansi:
      enabled: always # 디버깅 색 설정

logging:
  level:
    '[com.mtcoding.demo]': DEBUG # 로깅 레벨 -> 패키지 